Create srujan0404.md
SST-OSS/club-onboarding pull request #5
Opened 2023-09-18 11:20 UTC by srujan0404

2023-09-18 12:19 UTC, Diwakar-Gupta commented
you also need to describe the pr
have a look at this https://github.com/SST-OSS/club-onboarding/pull/3 you will get an idea

2023-09-18 21:59 UTC, Diwakar-Gupta requested changes

2023-09-18 21:59 UTC, Diwakar-Gupta commented on members/srujan0404.md
> +github_handle: srujan0404
Hey @srujan0404 this looks good but can you also describe the pr,
have a look at this https://github.com/SST-OSS/club-onboarding/pull/3 you will get an idea

2023-09-20 05:49 UTC, probablyArth commented
Srujan, please create a seperate PR for the java problems, solve one issue with 1 PR only.
Closing this one..

2023-09-20 05:49 UTC, closed without merging