Java problem 24 , test file updated
SST-OSS/club-onboarding pull request #76
Opened 2023-09-20 13:24 UTC by krishna-p060

test file updated according to requirement

2023-09-20 17:58 UTC, notpritam commented
Please follow the guidelines of Readme correctly, you have not provided the example input and output

2023-09-21 05:43 UTC, probablyArth commented
the readme still doesn't follow the one provided in the guide.
please go through it carefully

2023-09-21 09:29 UTC, probablyArth requested changes

2023-09-21 09:29 UTC, probablyArth commented on problem24/Solution.java
> +class Solution {
where is the solve method??

2023-09-21 09:29 UTC, probablyArth commented on problem24/Test.java
> +public class SolutionTest {
The class is supposed to be named `Test`

2023-09-21 09:30 UTC, probablyArth commented
also please mention the issue # this solves

2023-09-21 17:08 UTC, AbhinavGupta-de commented
@probablyArth LGTM!

2023-09-21 18:30 UTC, probablyArth approved these changes

2023-09-21 18:30 UTC, merged